CREATE DATABASE votaciones2503816; 
USE votaciones2503816; 

# CREACION DE TABLAS

CREATE TABLE Genero(
idGenero INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
nomGenero VARCHAR (10) NOT NULL,
estadoG BOOL NOT NULL
);

CREATE TABLE Jornada(
idJornada INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
nomJornada VARCHAR(20) NOT NULL,
estadoJ BOOL NOT NULL
);

CREATE TABLE TipoDocumento(
idTipoDoc INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nomTipoDoc VARCHAR(15) NOT NULL,
estadoTD BOOL NOT NULL
);

CREATE TABLE TipoMiembro(
idTipoMiembro INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nomTipoMiembro VARCHAR(20) NOT NULL,
estadoTM BOOL NOT NULL
);

CREATE TABLE Curso(
idCurso INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nomCurso VARCHAR(20) NOT NULL,
estadoCu BOOL NOT NULL
);

CREATE TABLE Concejo(
idCurso INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nomCurso VARCHAR(20) NOT NULL,
estadoCu BOOL NOT NULL
);

CREATE TABLE Cargo(
idCargo INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nomCargo VARCHAR(20) NOT NULL,
idConsejoFK INT NOT NULL,
estadoC BOOL NOT NULL
);

CREATE TABLE Eleccion(
idEleccion INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
fechaEleccion VARCHAR(20) NOT NULL,
anioEleccion VARCHAR(12) NOT NULL,
estadoEL BOOL NOT NULL
);

CREATE TABLE Usuario(
idUsuario INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
noDocUsuario VARCHAR(12) NOT NULL,
idTipoDocFK INT NOT NULL,
nombreUsuario VARCHAR(30) NOT NULL,
apellidoUsuario VARCHAR(30) NOT NULL,
idGeneroFK INT NOT NULL,
fechaNacUsuario VARCHAR(12) NOT NULL,
emailUsuario VARCHAR(30) NOT NULL,
passwordUsuario VARCHAR(30) NOT NULL,
fotoUsuario BLOB(777),
idJornadaFK INT NOT NULL,
idTipoMiembroFK INT NOT NULL,
idCursoFK INT NOT NULL,
FOREIGN KEY(idcursoFK) REFERENCES curso(idCurso)
);

CREATE TABLE Votacion(
idVotacion INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
horaVotacion VARCHAR(15) NOT NULL,
idUsuarioVotanteFK INT NOT NULL,
idPostCandidatoFK INT NOT NULL,
estadoV BOOL NOT NULL
);
